In [1]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2], [3, 4]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Construct the diagonal matrix Sigma from the singular values
# Sigma is m x n where m = 2 and n = 2 for this example
Sigma = np.zeros_like(A, dtype=float)
Sigma[:len(S), :len(S)] = np.diag(S)

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix U (left singular vectors):")
print(U)

print("\nMatrix Sigma (diagonal matrix with singular values):")
print(Sigma)

print("\nMatrix V^T (right singular vectors transposed):")
print(VT)

# Reconstruct the original matrix A from U, Sigma, and VT
A_reconstructed = np.dot(U, np.dot(Sigma, VT))

print("\nReconstructed Matrix A:")
print(A_reconstructed)


Matrix A:
[[1 2]
 [3 4]]

Matrix U (left singular vectors):
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Matrix Sigma (diagonal matrix with singular values):
[[5.4649857  0.        ]
 [0.         0.36596619]]

Matrix V^T (right singular vectors transposed):
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

Reconstructed Matrix A:
[[1. 2.]
 [3. 4.]]


In [2]:
import numpy as np

# Define a function to simulate an MZI with a coupler matrix
def mzi_matrix(phase_shift):
    # 50:50 coupler matrix
    coupler = np.array([
        [1/np.sqrt(2), 1/np.sqrt(2)],
        [1/np.sqrt(2), -1/np.sqrt(2)]
    ])
    
    # Phase shift matrix
    phase_shift_matrix = np.array([
        [1, 0],
        [0, np.exp(1j * phase_shift)]
    ])
    
    # Overall MZI matrix (simplified for this example)
    # Assuming the MZI involves a coupler followed by a phase shift and then another coupler
    mzi = coupler @ phase_shift_matrix @ coupler
    
    return mzi

# Define phase shift (in radians)
phase_shift = np.pi / 4  # Example phase shift

# Compute the MZI matrix
mzi = mzi_matrix(phase_shift)

# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(mzi)

# Display results
print("MZI Matrix:")
print(mzi)

print("\nU Matrix:")
print(U)

print("\nS Matrix (singular values):")
print(S)

print("\nVt Matrix:")
print(Vt)

# Note: S is returned as a 1D array of singular values; you may need to reconstruct the diagonal matrix
S_matrix = np.diag(S)
print("\nDiagonal Matrix Σ:")
print(S_matrix)


MZI Matrix:
[[0.85355339+0.35355339j 0.14644661-0.35355339j]
 [0.14644661-0.35355339j 0.85355339+0.35355339j]]

U Matrix:
[[-0.85355339-0.35355339j -0.31796708+0.21294024j]
 [-0.14644661+0.35355339j -0.51408321-0.76764044j]]

S Matrix (singular values):
[1. 1.]

Vt Matrix:
[[-1.        +0.j        -0.        +0.j       ]
 [ 0.        +0.j        -0.83205029+0.5547002j]]

Diagonal Matrix Σ:
[[1. 0.]
 [0. 1.]]
