In [1]:
import numpy as np
X = np.array([[1, 0.5, -1, 0.3], [1, -1, -2, -2], [1, 1.5, 0.2, -2.5]])
y = np.array([1, -1, 1])
C = 1/3
weights = np.array([0,0,0,0])
lr = [0.01, 0.005, 0.0025]

X_len = np.arange(len(X))


for epoch in range(len(lr)):
    print("Epoch: %d" % epoch)
    for i in X_len:
        print("ywx:", np.sign(y[i]) * np.dot(weights, X[i]))
        if np.sign(y[i]) * np.dot(weights, X[i]) <= 1:
            print("update for ywx<1")
            nweights = weights.copy()
            nweights[0] = 0
            weights = weights - lr[epoch]*nweights + lr[epoch]*C*len(X_len)*np.sign(y[i])*X[i]

        else:
            print("update for ywx>1")
            weights = (1-lr[epoch])*weights

        print(weights)

print("after 3 steps ")
print(weights)

Epoch: 0
ywx: 0.0
update for ywx<1
[ 0.01   0.005 -0.01   0.003]
ywx: -0.018999999999999996
update for ywx<1
[0.      0.01495 0.0101  0.02297]
ywx: -0.03297999999999999
update for ywx<1
[ 0.01       0.0298005  0.011999  -0.0022597]
Epoch: 1
ywx: 0.01222334
update for ywx<1
[ 0.015      0.0321515  0.006939  -0.0007484]
ywx: 0.0295327045
update for ywx<1
[0.01       0.03699074 0.01690431 0.00925534]
ywx: 0.045728620744999976
update for ywx<1
[ 0.015       0.04430579  0.01781979 -0.00329094]
Epoch: 2
ywx: 0.018345823872582497
update for ywx<1
[ 0.0175      0.04544502  0.01527524 -0.00253271]
ywx: 0.05343008204568096
update for ywx<1
[0.015      0.04783141 0.02023705 0.00247362]
ywx: 0.08461046681542886
update for ywx<1
[ 0.0175      0.05146183  0.02068646 -0.00378256]
after 3 steps 
[ 0.0175      0.05146183  0.02068646 -0.00378256]
